---
spec/spec_helper.rb:
  mock_with: ':rspec'
.travis.yml:
  remove_includes:
    - env: CHECK=parallel_spec
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
